aws_region         = "ap-south-1"
project            = "library"
vpc_cidr           = "10.20.0.0/16"
public_subnet_cidr = "10.20.1.0/24"
instance_type      = "t3.micro"
allowed_ssh_cidr   = "0.0.0.0/0"
bucket_name        = "library-assets-abdurrahmaan"
