apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library-data
  namespace: library-prod
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
