apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lib.name" . }}-config
  labels: {{- include "lib.labels" . | nindent 4 }}
data:
  LIBRARY_NAME: {{ .Values.config.libraryName | quote }}
  LOAN_DAYS: {{ .Values.config.loanDays | quote }}
  DATA_DIR: /data
