apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lib.name" . }}-books
  labels: {{- include "lib.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
