apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lib.name" . }}-secret
  labels: {{- include "lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_TOKEN: {{ .Values.secret.adminToken | quote }}
