apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-web
  namespace: troubleshoot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-web
  template:
    metadata:
      labels:
        app: library-web
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
